#!/usr/bin/env python3

import sys
from astropy.time import Time

try:
    ts = Time(sys.argv[1:], format='mjd')
    for t in ts:
        print(t.gps)
except:
    print("error: arguments must be numbers that represent MJD times")
